name: SpawnPlugin
version: '1.0-SNAPSHOT'
main: com.github.diogodashresende.spawnPlugin.SpawnPlugin
api-version: '1.21'
commands:
  setspawn:
    description: Set the server spawn point
  spawn:
    description: Spawns you at the spawn points